// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cisco.diddo.entity;

import com.cisco.diddo.dao.ExitCriteraDao;
import com.cisco.diddo.entity.ExitCriteriaDataOnDemand;
import com.cisco.diddo.entity.ExitCriteriaIntegrationTest;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect ExitCriteriaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExitCriteriaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExitCriteriaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private ExitCriteriaDataOnDemand ExitCriteriaIntegrationTest.dod;
    
    @Autowired
    ExitCriteraDao ExitCriteriaIntegrationTest.exitCriteraDao;
    
    @Test
    public void ExitCriteriaIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ExitCriteria' failed to initialize correctly", dod.getRandomExitCriteria());
        long count = exitCriteraDao.count();
        Assert.assertTrue("Counter for 'ExitCriteria' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExitCriteriaIntegrationTest.testFind() {
        ExitCriteria obj = dod.getRandomExitCriteria();
        Assert.assertNotNull("Data on demand for 'ExitCriteria' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExitCriteria' failed to provide an identifier", id);
        obj = exitCriteraDao.findOne(id);
        Assert.assertNotNull("Find method for 'ExitCriteria' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ExitCriteria' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExitCriteriaIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ExitCriteria' failed to initialize correctly", dod.getRandomExitCriteria());
        long count = exitCriteraDao.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ExitCriteria', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ExitCriteria> result = exitCriteraDao.findAll();
        Assert.assertNotNull("Find all method for 'ExitCriteria' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ExitCriteria' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExitCriteriaIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ExitCriteria' failed to initialize correctly", dod.getRandomExitCriteria());
        long count = exitCriteraDao.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ExitCriteria> result = exitCriteraDao.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ExitCriteria' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ExitCriteria' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExitCriteriaIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ExitCriteria' failed to initialize correctly", dod.getRandomExitCriteria());
        ExitCriteria obj = dod.getNewTransientExitCriteria(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ExitCriteria' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ExitCriteria' identifier to be null", obj.getId());
        exitCriteraDao.save(obj);
        Assert.assertNotNull("Expected 'ExitCriteria' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExitCriteriaIntegrationTest.testDelete() {
        ExitCriteria obj = dod.getRandomExitCriteria();
        Assert.assertNotNull("Data on demand for 'ExitCriteria' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExitCriteria' failed to provide an identifier", id);
        obj = exitCriteraDao.findOne(id);
        exitCriteraDao.delete(obj);
        Assert.assertNull("Failed to remove 'ExitCriteria' with identifier '" + id + "'", exitCriteraDao.findOne(id));
    }
    
}
