// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cisco.diddo.entity;

import com.cisco.diddo.entity.ExitCriteriaDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ExitCriteriaDataOnDemand_Roo_Configurable {
    
    declare @type: ExitCriteriaDataOnDemand: @Configurable;
    
}
