// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cisco.diddo.entity;

import com.cisco.diddo.entity.ImpedimentIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ImpedimentIntegrationTest_Roo_Configurable {
    
    declare @type: ImpedimentIntegrationTest: @Configurable;
    
}
