// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cisco.diddo.entity;

import com.cisco.diddo.dao.ScrumMasterDao;
import com.cisco.diddo.entity.ScrumMasterDataOnDemand;
import com.cisco.diddo.entity.ScrumMasterIntegrationTest;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect ScrumMasterIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ScrumMasterIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ScrumMasterIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private ScrumMasterDataOnDemand ScrumMasterIntegrationTest.dod;
    
    @Autowired
    ScrumMasterDao ScrumMasterIntegrationTest.scrumMasterDao;
    
    @Test
    public void ScrumMasterIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ScrumMaster' failed to initialize correctly", dod.getRandomScrumMaster());
        long count = scrumMasterDao.count();
        Assert.assertTrue("Counter for 'ScrumMaster' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ScrumMasterIntegrationTest.testFind() {
        ScrumMaster obj = dod.getRandomScrumMaster();
        Assert.assertNotNull("Data on demand for 'ScrumMaster' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ScrumMaster' failed to provide an identifier", id);
        obj = scrumMasterDao.findOne(id);
        Assert.assertNotNull("Find method for 'ScrumMaster' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ScrumMaster' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ScrumMasterIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ScrumMaster' failed to initialize correctly", dod.getRandomScrumMaster());
        long count = scrumMasterDao.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ScrumMaster', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ScrumMaster> result = scrumMasterDao.findAll();
        Assert.assertNotNull("Find all method for 'ScrumMaster' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ScrumMaster' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ScrumMasterIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ScrumMaster' failed to initialize correctly", dod.getRandomScrumMaster());
        long count = scrumMasterDao.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ScrumMaster> result = scrumMasterDao.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ScrumMaster' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ScrumMaster' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ScrumMasterIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ScrumMaster' failed to initialize correctly", dod.getRandomScrumMaster());
        ScrumMaster obj = dod.getNewTransientScrumMaster(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ScrumMaster' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ScrumMaster' identifier to be null", obj.getId());
        scrumMasterDao.save(obj);
        Assert.assertNotNull("Expected 'ScrumMaster' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ScrumMasterIntegrationTest.testDelete() {
        ScrumMaster obj = dod.getRandomScrumMaster();
        Assert.assertNotNull("Data on demand for 'ScrumMaster' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ScrumMaster' failed to provide an identifier", id);
        obj = scrumMasterDao.findOne(id);
        scrumMasterDao.delete(obj);
        Assert.assertNull("Failed to remove 'ScrumMaster' with identifier '" + id + "'", scrumMasterDao.findOne(id));
    }
    
}
