// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cisco.diddo.entity;

import com.cisco.diddo.dao.SprintDao;
import com.cisco.diddo.entity.Sprint;
import com.cisco.diddo.entity.SprintDataOnDemand;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SprintDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SprintDataOnDemand: @Component;
    
    private Random SprintDataOnDemand.rnd = new SecureRandom();
    
    private List<Sprint> SprintDataOnDemand.data;
    
    @Autowired
    SprintDao SprintDataOnDemand.sprintDao;
    
    public Sprint SprintDataOnDemand.getNewTransientSprint(int index) {
        Sprint obj = new Sprint();
        setEndDate(obj, index);
        setReleaseVersion(obj, index);
        setSprintNo(obj, index);
        setStartDate(obj, index);
        return obj;
    }
    
    public void SprintDataOnDemand.setEndDate(Sprint obj, int index) {
        Calendar endDate = Calendar.getInstance();
        obj.setEndDate(endDate);
    }
    
    public void SprintDataOnDemand.setReleaseVersion(Sprint obj, int index) {
        String releaseVersion = "releaseVersion_" + index;
        obj.setReleaseVersion(releaseVersion);
    }
    
    public void SprintDataOnDemand.setSprintNo(Sprint obj, int index) {
        String sprintNo = "sprintNo_" + index;
        obj.setSprintNo(sprintNo);
    }
    
    public void SprintDataOnDemand.setStartDate(Sprint obj, int index) {
        Calendar startDate = Calendar.getInstance();
        obj.setStartDate(startDate);
    }
    
    public Sprint SprintDataOnDemand.getSpecificSprint(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Sprint obj = data.get(index);
        BigInteger id = obj.getId();
        return sprintDao.findOne(id);
    }
    
    public Sprint SprintDataOnDemand.getRandomSprint() {
        init();
        Sprint obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return sprintDao.findOne(id);
    }
    
    public boolean SprintDataOnDemand.modifySprint(Sprint obj) {
        return false;
    }
    
    public void SprintDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = sprintDao.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Sprint' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Sprint>();
        for (int i = 0; i < 10; i++) {
            Sprint obj = getNewTransientSprint(i);
            try {
                sprintDao.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
