// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cisco.diddo.entity;

import com.cisco.diddo.dao.SprintDao;
import com.cisco.diddo.entity.SprintDataOnDemand;
import com.cisco.diddo.entity.SprintIntegrationTest;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect SprintIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SprintIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SprintIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private SprintDataOnDemand SprintIntegrationTest.dod;
    
    @Autowired
    SprintDao SprintIntegrationTest.sprintDao;
    
    @Test
    public void SprintIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Sprint' failed to initialize correctly", dod.getRandomSprint());
        long count = sprintDao.count();
        Assert.assertTrue("Counter for 'Sprint' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SprintIntegrationTest.testFind() {
        Sprint obj = dod.getRandomSprint();
        Assert.assertNotNull("Data on demand for 'Sprint' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sprint' failed to provide an identifier", id);
        obj = sprintDao.findOne(id);
        Assert.assertNotNull("Find method for 'Sprint' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Sprint' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SprintIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Sprint' failed to initialize correctly", dod.getRandomSprint());
        long count = sprintDao.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Sprint', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Sprint> result = sprintDao.findAll();
        Assert.assertNotNull("Find all method for 'Sprint' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Sprint' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SprintIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Sprint' failed to initialize correctly", dod.getRandomSprint());
        long count = sprintDao.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Sprint> result = sprintDao.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Sprint' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Sprint' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SprintIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Sprint' failed to initialize correctly", dod.getRandomSprint());
        Sprint obj = dod.getNewTransientSprint(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Sprint' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Sprint' identifier to be null", obj.getId());
        sprintDao.save(obj);
        Assert.assertNotNull("Expected 'Sprint' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SprintIntegrationTest.testDelete() {
        Sprint obj = dod.getRandomSprint();
        Assert.assertNotNull("Data on demand for 'Sprint' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sprint' failed to provide an identifier", id);
        obj = sprintDao.findOne(id);
        sprintDao.delete(obj);
        Assert.assertNull("Failed to remove 'Sprint' with identifier '" + id + "'", sprintDao.findOne(id));
    }
    
}
