// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cisco.diddo.entity;

import com.cisco.diddo.dao.UserStoryDao;
import com.cisco.diddo.entity.UserStoryDataOnDemand;
import com.cisco.diddo.entity.UserStoryIntegrationTest;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect UserStoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserStoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserStoryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private UserStoryDataOnDemand UserStoryIntegrationTest.dod;
    
    @Autowired
    UserStoryDao UserStoryIntegrationTest.userStoryDao;
    
    @Test
    public void UserStoryIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'UserStory' failed to initialize correctly", dod.getRandomUserStory());
        long count = userStoryDao.count();
        Assert.assertTrue("Counter for 'UserStory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserStoryIntegrationTest.testFind() {
        UserStory obj = dod.getRandomUserStory();
        Assert.assertNotNull("Data on demand for 'UserStory' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserStory' failed to provide an identifier", id);
        obj = userStoryDao.findOne(id);
        Assert.assertNotNull("Find method for 'UserStory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserStory' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserStoryIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'UserStory' failed to initialize correctly", dod.getRandomUserStory());
        long count = userStoryDao.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserStory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserStory> result = userStoryDao.findAll();
        Assert.assertNotNull("Find all method for 'UserStory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserStory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserStoryIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'UserStory' failed to initialize correctly", dod.getRandomUserStory());
        long count = userStoryDao.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserStory> result = userStoryDao.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'UserStory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserStory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserStoryIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'UserStory' failed to initialize correctly", dod.getRandomUserStory());
        UserStory obj = dod.getNewTransientUserStory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserStory' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserStory' identifier to be null", obj.getId());
        userStoryDao.save(obj);
        Assert.assertNotNull("Expected 'UserStory' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserStoryIntegrationTest.testDelete() {
        UserStory obj = dod.getRandomUserStory();
        Assert.assertNotNull("Data on demand for 'UserStory' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserStory' failed to provide an identifier", id);
        obj = userStoryDao.findOne(id);
        userStoryDao.delete(obj);
        Assert.assertNull("Failed to remove 'UserStory' with identifier '" + id + "'", userStoryDao.findOne(id));
    }
    
}
